server:
  port: 10000
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/XieGang2?useSSL=false
      username: haha
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      #druid连接池配置
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 基础监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #设置不统计哪些URL
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 100
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        #设置监控页面的登录名和密码
        login-username: admin
        login-password: 123456
        allow:


  servlet:
    #上传文件设置
    multipart:
      max-file-size: 6MB
      max-request-size: 20MB

  redis:
    host: 127.0.0.1
    port: 6379
    password: root

    client-type: jedis
    jedis:
      pool:
        max-active: 8
        max-wait: 3
        max-idle: 10
        min-idle: 1


#log配置
logging:
  file:
    name: ./logs/logger.log
  level.root: info


#阿里云OSS
# AccessKey 在AccessKey管理获取 -->登录后-->头像-->AccessKey管理
OSS:
  end-point: "oss-cn-beijing.aliyuncs.com"
  access-key: "hahaha"
  access-key-secret: "hahaha"
  bucket: "hahaha"
  pic-url: "hahaha"